(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Sysaysbackground300x600 = function() {
	this.initialize(img.Sysaysbackground300x600);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,350,650);


(lib.Symbol2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Sysaysbackground300x600();
	this.instance.setTransform(0,0,1.0515,1.0514);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,368,683.5);


(lib.nestedlogofromsysays = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_6_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F4EFEF").s().p("A3aQkQhEhEAAhpQAAhpBEhDQBChCBmAAQBmAAA8A7QA4A3AHBaIh3AEQgOhihdAAQgxAAgeAjQgcAiAAA7QAAA8AcAiQAeAjAxAAQBdAAAOhjIB3AFQgHBag4A3Qg8A7hmAAQhmAAhChCgEAnsARdIAAnMIDLAAQBaAAAzApQAxApAABMQAABMgxAqQgzAphaAAIhPAAIAACPgEApoANqIBJAAQBMAAABg6QgBg7hMAAIhJAAgEAg8ARdIAAnMIDLAAQBaAAAyApQAyApgBBMQABBMgyAqQgyAphaAAIhQAAIAACPgEAi3ANqIBJAAQBNAAAAg6QAAg7hNAAIhJAAgAeVRdIgjhZIizAAIgiBZIh9AAIC3nMICLAAIC3HMgAdPOnIg1iHIgCAAIg1CHIBsAAgAMuRdIAAnMIFjAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDxAAIAABmgAruRdIAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACyIC3AAIAAiyIB9AAIAAHMgA3aHWQhEhEAAhpQAAhpBEhDQBChCBmAAQBmAAA8A7QA4A3AHBaIh3AEQgOhihdAAQgxAAgeAjQgcAiAAA7QAAA8AcAiQAeAjAxAAQBdAAAOhjIB3AFQgHBag4A3Qg8A7hmAAQhmAAhChCgEAmBAIPIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgAYgIPIAAnMIDLAAQBaAAAyApQAyApgBBMQABBMgyAqQgyAphaAAIhQAAIAACPgAabEcIBJAAQBNAAAAg6QAAg7hNAAIhJAAgAF9IPIAAnMIDLAAQBaAAAyApQAyApgBBMQABBMgyAqQgyAphaAAIhQAAIAACPgAH4EcIBJAAQBNAAAAg6QAAg7hNAAIhJAAgAjZIPIgjhZIi0AAIgiBZIh9AAIC4nMICKAAIC4HMgAkgFZIg1iHIgCAAIg1CHIBsAAgAruIPIAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACyIC3AAIAAiyIB9AAIAAHMgEgswgBxQhEhDAAhpQAAhpBEhEQBChCBlAAQBnAAA8A7QA4A3AGBbIh3AEQgNhjhdAAQgyAAgdAjQgdAjAAA7QAAA7AdAiQAdAjAyAAQBdAAANhiIB3AFQgGBag4A2Qg8A8hnAAQhlAAhChDgEghEgA3IAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACxIC3AAIAAixIB8AAIAAHMgAMuhAIAAnMIFjAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDxAAIAABmgAF9hAIAAnMIDLAAQBaAAAyApQAyApgBBMQABBMgyAqQgyAphaAAIhQAAIAACPgAH4kzIBJAAQBNAAAAg6QAAg7hNAAIhJAAgAgzhAIAAnMIDKAAQBaAAAzApQAxApAABMQAABMgxAqQgzAphaAAIhPAAIAACPgABIkzIBJAAQBMAAABg6QgBg7hMAAIhJAAgAjZhAIgjhZIi0AAIgiBZIh9AAIC4nMICKAAIC4HMgAkgj2Ig1iHIgCAAIg1CHIBsAAgEglRgLKQhDhEAAhpQAAhpBDhDQBChCBmAAQBmAAA9A7QA4A3AGBaIh3AEQgOhihcAAQgzAAgcAjQgdAiAAA7QAAA8AdAiQAcAjAzAAQBcAAAOhjIB3AFQgGBag4A3Qg9A7hmAAQhmAAhChCgAeHqZIAAnMIDLAAQBbAAAxApQAyApAABLQAABNgyApQgxAphbAAIhPAAIAACQgEAgDgOMIBJAAQBMAAABg7QgBg7hMAAIhJAAgAMuqZIAAnMIFjAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDxAAIAABngAgzqZIAAnMIDKAAQBaAAAzApQAxApAABLQAABNgxApQgzAphaAAIhPAAIAACQgABIuMIBJAAQBMAAABg7QgBg7hMAAIhJAAgAjZqZIgjhZIi0AAIgiBZIh9AAIC4nMICKAAIC4HMgAkgtPIg1iIIgCAAIg1CIIBsAAgAruqZIAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACxIC3AAIAAixIB9AAIAAHMg");
	this.shape.setTransform(450.6,523.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F4EFEF").s().p("Egm2AQsQhDhDAAhpQAAhpBDhEQBDhCBmAAQBmAAA8A7QA4A3AHBbIh4AEQgOhjhcAAQgyAAgdAjQgcAjAAA7QAAA7AcAiQAdAjAyAAQBcAAAOhiIB4AFQgHBag4A2Qg8A8hmAAQhmAAhDhDgAeyRdIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgAIMRdIAAnMIDLAAQBaAAAyApQAyApgBBMQABBMgyAqQgyAphaAAIhQAAIAACPgAKHNqIBJAAQBNAAAAg6QAAg7hNAAIhJAAgABbRdIAAnMIDLAAQBaAAAzApQAxApAABMQAABMgxAqQgzAphaAAIhPAAIAACPgADXNqIBJAAQBMAAABg6QgBg7hMAAIhJAAgAhKRdIgjhZIi0AAIgiBZIh9AAIC4nMICKAAIC3HMgAiROnIg1iHIgCAAIg1CHIBsAAgApfRdIAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACyIC3AAIAAiyIB9AAIAAHMgA1LHWQhEhEAAhpQAAhpBEhDQBChCBmAAQBmAAA8A7QA4A3AHBaIh3AEQgOhihdAAQgxAAgeAjQgcAiAAA7QAAA8AcAiQAeAjAxAAQBdAAAOhjIB3AFQgHBag4A3Qg8A7hmAAQhmAAhChCgEAzAAIPIAAnMIDKAAQBbAAAyApQAxApAABMQAABMgxAqQgyAphbAAIhPAAIAACPgEA07AEcIBJAAQBMAAAAg6QAAg7hMAAIhJAAgEApoAIPIgjhZIizAAIgiBZIh9AAIC3nMICLAAIC3HMgEAoiAFZIg1iHIgDAAIg0CHIBsAAgEAhTAIPIAAi2Ii2AAIAAC2Ih8AAIAAnMIB8AAIAACyIC2AAIAAiyIB9AAIAAHMgAO9IPIAAnMIFjAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDxAAIAABmgABbIPIAAnMIDLAAQBaAAAzApQAxApAABMQAABMgxAqQgzAphaAAIhPAAIAACPgADXEcIBJAAQBMAAABg6QgBg7hMAAIhJAAgEglogBxQhEhDAAhpQAAhpBEhEQBChCBmAAQBmAAA8A7QA4A3AHBbIh3AEQgOhjhdAAQgxAAgeAjQgcAjAAA7QAAA7AcAiQAeAjAxAAQBdAAAOhiIB3AFQgHBag4A2Qg8A8hmAAQhmAAhChDgEAxAgBAIAAnMIFjAAIAABmIjpAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgEAjfgBAIAAnMIDKAAQBbAAAyApQAxApAABMQAABMgxAqQgyAphbAAIhPAAIAACPgEAlagEzIBJAAQBNAAAAg6QAAg7hNAAIhJAAgEAg4gBAIgjhZIizAAIgiBZIh9AAIC3nMICLAAIC3HMgAfyj2Ig1iHIgDAAIg0CHIBsAAgAIMhAIAAnMIDLAAQBaAAAyApQAyApgBBMQABBMgyAqQgyAphaAAIhQAAIAACPgAKHkzIBJAAQBNAAAAg6QAAg7hNAAIhJAAgApfhAIAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACyIC3AAIAAiyIB9AAIAAHMgA1LrTQhEhDAAhpQAAhpBEhEQBChCBmAAQBmAAA8A7QA4A3AHBbIh3AEQgOhjhdAAQgxAAgeAjQgcAjAAA7QAAA7AcAiQAeAjAxAAQBdAAAOhiIB3AFQgHBag4A2Qg8A8hmAAQhmAAhChDgAO9qZIAAnMIFjAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDxAAIAABngAhKqZIgjhZIi0AAIgiBZIh9AAIC4nMICKAAIC3HMgAiRtPIg1iIIgCAAIg1CIIBsAAgEgiogKZIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgEggsgOMIBJAAQBMAAAAg7QAAg7hMAAIhJAAgEgpYgKZIAAnMIDKAAQBbAAAxApQAyApAABLQAABNgyApQgxAphbAAIhPAAIAACQgEgndgOMIBJAAQBNAAgBg7QABg7hNAAIhJAAgEg0UgKZIAAi2Ii3AAIAAC2Ih8AAIAAnMIB8AAIAACxIC3AAIAAixIB8AAIAAHMg");
	this.shape_1.setTransform(436.3,523.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F4EFEF").s().p("APxRmIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJARmIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyApQgyAqhaAAIhPAAIAACPgAK8NzIBJAAQBMAAAAg7QAAg6hMAAIhJAAgACQRmIAAnMIDKAAQBbAAAyApQAxApABBMQgBBMgxApQgyAqhbAAIhOAAIAACPgAEMNzIBJAAQBMAAAAg7QAAg6hMAAIhJAAgAorRmIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XHfQhDhEAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A8QA4A2AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAjQAdAiAyABQBcAAAPhjIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhCgAJAIYIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyAqQgyAphagBIhPAAIAACQgAK8ElIBJAAQBMAAAAg6QAAg8hMABIhJAAgACQIYIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxAqQgyAphbgBIhOAAIAACQgAEMElIBJAAQBMAAAAg6QAAg8hMABIhJAAgAJAg3IAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAohaAAIhPAAIAACQgAK8kqIBJAAQBMAAAAg6QAAg8hMAAIhJAAgAorqIIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACyIC2AAIAAiyIB9AAIAAHMgA0XrKQhDhDAAhpQAAhqBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AFQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhjIB3AGQgHBZg4A3Qg9A8hlgBQhmAAhDhCgAPxqRIAAnMIFkAAIAABnIjqAAIAABLIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_2.setTransform(431.05,522.9);
	this.shape_2._off = true;

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F4EFEF").s().p("AMHRmIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAFWRmIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyApQgyAqhaAAIhPAAIAACPgAHSNzIBJAAQBMAAAAg7QAAg6hMAAIhJAAgAhZRmIAAnMIDJAAQBbAAAyApQAxApABBMQgBBMgxApQgyAqhbAAIhOAAIAACPgAAiNzIBJAAQBMAAAAg7QAAg6hMAAIhJAAgAsVRmIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA4BHfQhDhEAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A8QA4A2AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAjQAdAiAyABQBcAAAPhjIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhCgAFWIYIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyAqQgyAphagBIhPAAIAACQgAHSElIBJAAQBMAAAAg6QAAg8hMABIhJAAgAhZIYIAAnMIDJAAQBbAAAyApQAxApABBLQgBBNgxAqQgyAphbgBIhOAAIAACQgAAiElIBJAAQBMAAAAg6QAAg8hMABIhJAAgAYNg3IA4iLIAACLgAFWg3IAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAohaAAIhPAAIAACQgAHSkqIBJAAQBMAAAAg6QAAg8hMAAIhJAAgAsVqIIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACyIC2AAIAAiyIB9AAIAAHMgA4BrKQhDhDAAhpQAAhqBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AFQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhjIB3AGQgHBZg4A3Qg9A8hlgBQhmAAhDhCgAMHqRIAAnMIFkAAIAABnIjqAAIAABLIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_3.setTransform(454.45,522.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F4EFEF").s().p("A0XQoQhDhDAAhqQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AFQgPhjhcAAQgyAAgdAjQgdAjABA6QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AGQgHBag4A2Qg9A8hlAAQhmAAhDhDgAPxRZIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJARZIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAqhaAAIhPAAIAACPgAK8NmIBJAAQBMAAAAg7QAAg6hMAAIhJAAgACQRZIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAqhbAAIhOAAIAACPgAEMNmIBJAAQBMAAAAg7QAAg6hMAAIhJAAgAorRZIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XHSQhDhEAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A8QA4A2AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAjQAdAiAyABQBcAAAPhjIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhCgAJAILIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyAqQgyAphagBIhPAAIAACQgAK8EYIBJAAQBMAAAAg6QAAg8hMABIhJAAgACQILIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxAqQgyAphbgBIhOAAIAACQgAEMEYIBJAAQBMAAAAg6QAAg8hMABIhJAAgAgWILIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcFVIg1iHIgDAAIg0CHIBsAAgA0Xh1QhDhEAAhoQAAhqBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3ADQgPhihcAAQgyAAgdAjQgdAiABA8QgBA7AdAiQAdAjAyAAQBcAAAPhjIB3AGQgHBZg4A3Qg9A7hlAAQhmAAhDhCgAPxhEIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgAJAhEIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAohaAAIhPAAIAACQgAK8k3IBJAAQBMAAAAg6QAAg8hMAAIhJAAgAgGhEIgihZIi0AAIghBZIh9AAIC2nMICMAAIC2HMgAhMj6Ig0iIIgDAAIg1CIIBsAAgAgWqVIgihYIi0AAIgiBYIh9AAIC3nMICLAAIC2HMgAhctLIg1iHIgDAAIg0CHIBsAAgAorqVIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACyIC2AAIAAiyIB9AAIAAHMgAPxqeIAAnMIFkAAIAABnIjqAAIAABLIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_4.setTransform(431.05,524.2);
	this.shape_4._off = true;

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#F4EFEF").ss(1,1,1).p("AAAgFIAAAL");
	this.shape_5.setTransform(599.35,657.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F4EFEF").s().p("APxRiIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJARiIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8NvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQRiIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMNvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWRiIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjIOsIBsAAIg1iIIgDAAgA0XHaQhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAJAIUIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8EhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQIUIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMEhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWIUIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjIFeIBsAAIg1iIIgDAAgA0XhsQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAPxg7IAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJAg7IAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8kuIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgGg7IgihZIi0AAIghBZIh9AAIC2nMICMAAIC2HMgAi4jxIBsAAIg0iIIgDAAgAorg7IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0Xq9QhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAgWqMIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjItCIBsAAIg1iHIgDAAgAPxqVIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_6.setTransform(431.05,523.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F4EFEF").s().p("ACQRiIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMNvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWRiIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcOsIg1iIIgDAAIg0CIIBsAAgA0XHaQhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAPxIUIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJAIUIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8EhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAorIUIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XhsQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAPxg7IAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAgGg7IgihZIi0AAIghBZIh9AAIC2nMICMAAIC2HMgAhMjxIg0iIIgDAAIg1CIIBsAAgAorg7IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0Xq9QhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAJAqMIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAphaAAIhPAAIAACPgAK8t/IBJAAQBMAAAAg6QAAg7hMAAIhJAAgAPxqVIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_7.setTransform(431.05,523.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F4EFEF").s().p("AJARiIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8NvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQRiIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMNvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWRiIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjIOsIBsAAIg1iIIgDAAgA0XHaQhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAPxIUIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJAIUIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8EhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWIUIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjIFeIBsAAIg1iIIgDAAgAorIUIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XhsQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAPxg7IAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAgGg7IgihZIi0AAIghBZIh9AAIC2nMICMAAIC2HMgAi4jxIBsAAIg0iIIgDAAgAorg7IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgAJAqMIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAphaAAIhPAAIAACPgAK8t/IBJAAQBMAAAAg6QAAg7hMAAIhJAAgAPxqVIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_8.setTransform(431.05,523.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#F4EFEF").ss(1,1,1).p("AAAAJIAAgR");
	this.shape_9.setTransform(268.5,349.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F4EFEF").s().p("A0XQkQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAPxRdIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgAorRdIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACyIC2AAIAAiyIB9AAIAAHMgA0XHWQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAJAIPIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAphaAAIhPAAIAACPgAK8EcIBJAAQBMAAAAg6QAAg7hMAAIhJAAgAgWIPIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjIFZIBsAAIg1iHIgDAAgAorIPIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACyIC2AAIAAiyIB9AAIAAHMgAPxhAIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgAJAhAIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAphaAAIhPAAIAACPgAK8kzIBJAAQBMAAAAg6QAAg7hMAAIhJAAgACQhAIAAnMIDKAAQBbAAAyApQAxApABBMQgBBMgxAqQgyAphbAAIhOAAIAACPgAEMkzIBJAAQBMAAAAg6QAAg7hMAAIhJAAgAPxqZIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngACQqZIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMuMIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWqZIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAjItPIBsAAIg1iIIgDAAgAorqZIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMg");
	this.shape_10.setTransform(431.05,523.775);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F4EFEF").s().p("AJARiIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8NvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQRiIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMNvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWRiIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcOsIg1iIIgDAAIg0CIIBsAAgAorRiIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XHaQhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAPxIUIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngACQIUIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMEhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAJAg7IAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8kuIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAorg7IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgAPxqVIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgAgWqVIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhctLIg1iHIgDAAIg0CHIBsAAg");
	this.shape_11.setTransform(431.05,523.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F4EFEF").s().p("AJARmIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyApQgyAqhaAAIhPAAIAACPgAK8NzIBJAAQBMAAAAg7QAAg6hMAAIhJAAgACQRmIAAnMIDKAAQBbAAAyApQAxApABBMQgBBMgxApQgyAqhbAAIhOAAIAACPgAEMNzIBJAAQBMAAAAg7QAAg6hMAAIhJAAgAgWRmIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcOwIg1iIIgDAAIg0CIIBsAAgAorRmIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XHfQhDhEAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A8QA4A2AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAjQAdAiAyABQBcAAAPhjIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhCgAPxIYIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmgACQIYIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxAqQgyAphbgBIhOAAIAACQgAEMElIBJAAQBMAAAAg6QAAg8hMABIhJAAgAJAg3IAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAohaAAIhPAAIAACQgAK8kqIBJAAQBMAAAAg6QAAg8hMAAIhJAAgAorg3IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACyIC2AAIAAiyIB9AAIAAHMgA0XrKQhDhDAAhpQAAhqBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AFQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhjIB3AGQgHBZg4A3Qg9A8hlgBQhmAAhDhCgAPxqRIAAnMIFkAAIAABnIjqAAIAABLIC0AAIAABkIi0AAIAABQIDwAAIAABmgAgWqRIgihYIi0AAIgiBYIh9AAIC3nMICLAAIC2HMgAhctHIg1iHIgDAAIg0CHIBsAAg");
	this.shape_12.setTransform(431.05,522.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F4EFEF").s().p("APxRiIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJARiIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8NvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQRiIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMNvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWRiIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcOsIg1iIIgDAAIg0CIIBsAAgA0XHaQhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAJAIUIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8EhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQIUIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMEhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWIUIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcFeIg1iIIgDAAIg0CIIBsAAgA0XhsQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAPxg7IAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJAg7IAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8kuIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgGg7IgihZIi0AAIghBZIh9AAIC2nMICMAAIC2HMgAhMjxIg0iIIgDAAIg1CIIBsAAgAorg7IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0Xq9QhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAgWqMIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhctCIg1iHIgDAAIg0CHIBsAAgAPxqVIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_13.setTransform(431.05,523.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F4EFEF").s().p("APxRiIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJARiIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8NvIBJAAQBMAAAAg7QAAg7hMAAIhJAAgA0XHaQhDhDAAhpQAAhpBDhEQBDhCBmAAQBlAAA9A7QA4A3AHBbIh3AEQgPhjhcAAQgyAAgdAjQgdAjABA7QgBA7AdAiQAdAjAyAAQBcAAAPhiIB3AFQgHBag4A2Qg9A8hlAAQhmAAhDhDgAPxIUIAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAJAIUIAAnMIDLAAQBaAAAyApQAyApAABLQAABNgyApQgyAphaAAIhPAAIAACQgAK8EhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgACQIUIAAnMIDKAAQBbAAAyApQAxApABBLQgBBNgxApQgyAphbAAIhOAAIAACQgAEMEhIBJAAQBMAAAAg7QAAg7hMAAIhJAAgAgWIUIgihZIi0AAIgiBZIh9AAIC3nMICLAAIC2HMgAhcFeIg1iIIgDAAIg0CIIBsAAgAorIUIAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgA0XhsQhDhEAAhpQAAhpBDhDQBDhCBmAAQBlAAA9A7QA4A3AHBaIh3AEQgPhihcAAQgyAAgdAjQgdAiABA7QgBA8AdAiQAdAjAyAAQBcAAAPhjIB3AFQgHBag4A3Qg9A7hlAAQhmAAhDhCgAPxg7IAAnMIFkAAIAABmIjqAAIAABLIC0AAIAABlIi0AAIAABPIDwAAIAABngAgGg7IgihZIi0AAIghBZIh9AAIC2nMICMAAIC2HMgAhMjxIg0iIIgDAAIg1CIIBsAAgAorg7IAAi2Ii2AAIAAC2Ih9AAIAAnMIB9AAIAACxIC2AAIAAixIB9AAIAAHMgAJAqMIAAnMIDLAAQBaAAAyApQAyApAABMQAABMgyAqQgyAphaAAIhPAAIAACPgAK8t/IBJAAQBMAAAAg6QAAg7hMAAIhJAAgAPxqVIAAnMIFkAAIAABmIjqAAIAABMIC0AAIAABkIi0AAIAABQIDwAAIAABmg");
	this.shape_14.setTransform(431.05,523.325);
	this.shape_14._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},3).to({state:[{t:this.shape_1}]},4).to({state:[{t:this.shape_2}]},3).to({state:[{t:this.shape_3}]},4).to({state:[{t:this.shape_4}]},3).to({state:[{t:this.shape_6},{t:this.shape_5,p:{y:657.525}}]},4).to({state:[{t:this.shape_7}]},3).to({state:[{t:this.shape_8},{t:this.shape_5,p:{y:651.55}}]},3).to({state:[{t:this.shape_10},{t:this.shape_9}]},3).to({state:[{t:this.shape_11}]},3).to({state:[{t:this.shape_12}]},3).to({state:[{t:this.shape_2}]},3).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_4}]},3).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_7}]},3).to({state:[{t:this.shape_14}]},3).to({state:[{t:this.shape_14}]},9).to({state:[{t:this.shape_14}]},21).to({state:[{t:this.shape_14}]},40).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(10).to({_off:false},0).to({_off:true},4).wait(25).to({_off:false},0).wait(3).to({_off:true},3).wait(80));
	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(17).to({_off:false},0).to({_off:true},4).wait(24).to({_off:false},0).wait(2).to({_off:true},1).wait(77));
	this.timeline.addTween(cjs.Tween.get(this.shape_14).wait(54).to({_off:false},0).wait(71));

	// Layer_7_copy
	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F4EFEF").s().p("AjeDsQhchcAAiQQAAiPBchcQBbhbCLAAQCKAABTBRQBNBLAKB8IijAGQgUiHh+AAQhEAAgoAwQgnAvAABQQAABRAnAvQAoAwBEAAQB+AAAUiHICjAHQgKB7hNBLQhSBRiLAAQiLAAhbhbg");
	this.shape_15.setTransform(341.05,32.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_15).wait(125));

	// Layer_8_copy
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F4EFEF").s().p("AClE7Igvh6Ij1AAIgvB6IirAAID7p1IC9AAID7J1gABFBCIhHi5IgEAAIhIC5ICTAAg");
	this.shape_16.setTransform(409,32.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_16).wait(125));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(70.7,0,731.1999999999999,659.2);


(lib.GREENBACKGROUNDSYMBOL = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Sysaysbackground300x600();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,350,650);


// stage content:
(lib.Sysays300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// nested_logo_from_sysays
	this.instance = new lib.nestedlogofromsysays("synched",0);
	this.instance.setTransform(126.75,25.95,1,1,0,0,0,408.2,366.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(125));

	// Layer_9
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F4EFEF").s().p("AARAZIgGgPIgWAAIgGAPIgHAAIAVgxIAHAAIAVAxgAAJAFIgJgVIgJAVIASAAg");
	this.shape.setTransform(283.2,585.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F4EFEF").s().p("AgRAZIAAgxIAiAAIAAAGIgbAAIAAAPIAVAAIAAAFIgVAAIAAASIAcAAIAAAFg");
	this.shape_1.setTransform(278.6,585.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F4EFEF").s().p("AgNAVQgGgFAAgJIAGAAQAAAHAEADQAFAEAFAAQAGAAADgDQADgCAAgEQAAgDgCgCQgCgCgFgBIgJgCQgNgCAAgKQAAgHAFgEQAFgEAIAAQAIAAAGAFQAFAEABAJIgHAAQAAgGgEgDQgDgEgGAAQgFAAgDADQgDACAAAEQAAAEACACQADABAEABIAIACQAHABADACQAEAEAAAGQAAAGgGAEQgEAEgJAAQgJAAgFgFg");
	this.shape_2.setTransform(274.05,585.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F4EFEF").s().p("AgRAZIAAgxIAiAAIAAAGIgcAAIAAAPIAWAAIAAAFIgWAAIAAASIAdAAIAAAFg");
	this.shape_3.setTransform(268.4,585.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F4EFEF").s().p("AAPAZIAAgXIgcAAIAAAXIgHAAIAAgxIAHAAIAAAVIAcAAIAAgVIAHAAIAAAxg");
	this.shape_4.setTransform(263.5,585.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F4EFEF").s().p("AgDAZIAAgrIgSAAIAAgGIArAAIAAAGIgTAAIAAArg");
	this.shape_5.setTransform(258.5,585.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F4EFEF").s().p("AgDAZIAAgUIgTgdIAIAAIAPAYIAOgYIAIAAIgUAdIAAAUg");
	this.shape_6.setTransform(158.6,585.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F4EFEF").s().p("AgTAZIAAgxIAUAAQARAAAAANQAAAFgCADQgDACgEABQAFAAADADQADADAAAFQAAAHgFAEQgFADgIAAgAgMAUIANAAQAMAAAAgJQAAgJgMAAIgNAAgAgMgCIANAAQAKAAAAgIQAAgIgKAAIgNAAg");
	this.shape_7.setTransform(153.975,585.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F4EFEF").s().p("AgRAZIAAgxIAiAAIAAAGIgcAAIAAAPIAXAAIAAAFIgXAAIAAASIAdAAIAAAFg");
	this.shape_8.setTransform(52.85,585.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F4EFEF").s().p("AgNAVQgGgFAAgJIAGAAQABAHADADQAEAEAGAAQAGAAADgDQAEgCAAgEQAAgDgDgCQgCgCgFgBIgJgCQgNgCAAgKQABgHAEgEQAFgEAIAAQAJAAAFAFQAFAEAAAJIgGAAQAAgGgEgDQgEgEgFAAQgFAAgDADQgDACAAAEQAAAEACACQACABAFABIAIACQAIABADACQADAEAAAGQAAAGgFAEQgGAEgIAAQgIAAgGgFg");
	this.shape_9.setTransform(48.3,585.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F4EFEF").s().p("AgOAVQgFgFAAgLIAAgeIAGAAIAAAfQAAAOANAAQAOAAAAgOIAAgfIAGAAIAAAeQAAALgGAFQgFAFgJAAQgIAAgGgFg");
	this.shape_10.setTransform(43.675,586.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F4EFEF").s().p("AgRATQgHgHAAgMQAAgLAHgHQAHgHAKAAQALAAAHAHQAHAHAAALQAAAMgHAHQgHAHgLAAQgKAAgHgHgAgMgOQgFAGAAAIQAAAJAFAGQAFAFAHAAQAIAAAFgFQAFgGAAgJQAAgIgFgGQgFgFgIAAQgHAAgFAFg");
	this.shape_11.setTransform(38.45,585.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F4EFEF").s().p("AAPAZIAAgXIgcAAIAAAXIgHAAIAAgxIAHAAIAAAVIAcAAIAAgVIAHAAIAAAxg");
	this.shape_12.setTransform(33.1,585.975);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F4EFEF").s().p("AgCAZIAAgrIgTAAIAAgGIArAAIAAAGIgSAAIAAArg");
	this.shape_13.setTransform(26.7,585.975);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F4EFEF").s().p("AANAZQgCgCgBgJQAAgJgJAAIgNAAIAAAUIgHAAIAAgxIATAAQAJAAAGAEQAEAEAAAHQABAFgEAEQgDACgFAAQAJACABAJIAAAIIACAEgAgMAAIAMAAQAMAAAAgJQAAgJgMAAIgMAAg");
	this.shape_14.setTransform(22.1,585.975);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F4EFEF").s().p("AARAZIgGgPIgWAAIgFAPIgIAAIAVgxIAGAAIAWAxgAAJAFIgJgVIgIAVIARAAg");
	this.shape_15.setTransform(17.05,585.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},103).wait(22));

	// Layer_8
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F4EFEF").s().p("AgjApQgQgPAAgZQAAgXAPgRQAPgPAWAAQAYAAAOAPQANAOAAAXIAAAHIhTAAQABAPAKAKQAJAJANAAQAaAAAHgXIAQABQgEASgMAKQgNAKgUABQgWAAgPgPgAAfgHQAAgOgIgJQgIgJgOAAQgMAAgJAJQgIAJgCAOIA9AAIAAAAg");
	this.shape_16.setTransform(281.825,337.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F4EFEF").s().p("AgJBMIAAiWIATAAIAACWg");
	this.shape_17.setTransform(273.6,335.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F4EFEF").s().p("AgJBMIAAiWIATAAIAACWg");
	this.shape_18.setTransform(268.9,335.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F4EFEF").s().p("AgjApQgQgPAAgZQAAgXAPgRQAPgPAWAAQAYAAAOAPQANAOAAAXIAAAHIhTAAQABAPAKAKQAJAJANAAQAaAAAHgXIAQABQgEASgMAKQgNAKgUABQgWAAgPgPgAAfgHQAAgOgIgJQgIgJgOAAQgMAAgJAJQgIAJgCAOIA9AAIAAAAg");
	this.shape_19.setTransform(260.725,337.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F4EFEF").s().p("AgJBMIAAiWIATAAIAACWg");
	this.shape_20.setTransform(252.5,335.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F4EFEF").s().p("AglAoQgQgPAAgZQAAgXAQgQQAPgPAWAAQAXAAAPAPQAPAQAAAXQAAAZgPAPQgPAQgXAAQgWAAgPgQgAgXgbQgJAKAAARQAAASAJALQAIALAPAAQAPAAAJgLQAJgLAAgSQAAgRgJgKQgJgMgPAAQgPAAgIAMg");
	this.shape_21.setTransform(244.15,337.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F4EFEF").s().p("AgtAMIAAhBIAUAAIAAA/QAAAcAYAAQALAAAIgIQAIgKAAgOIAAg7IAUAAIAABoIgUAAIAAgTQgEAKgJAGQgKAGgKAAQgmAAAAgqg");
	this.shape_22.setTransform(232.175,337.95);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F4EFEF").s().p("Ag0BKIAAiQIAUAAIAAAWQAEgLAJgGQALgIANAAQAXAAANAQQAMAPAAAYQAAAYgMAPQgNAQgXAAQgNAAgLgIQgJgHgEgKIAAA+gAgWgvQgKAKAAAQIAAAGQAAAQAKAKQAIAKAOAAQAPAAAJgLQAIgKAAgSQAAgSgIgKQgJgLgPAAQgOAAgIAKg");
	this.shape_23.setTransform(220.4,339.675);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F4EFEF").s().p("AglAoQgQgPABgZQgBgXAQgQQAPgPAWAAQAXAAAPAPQAQAQAAAXQAAAZgQAPQgPAQgXAAQgWAAgPgQgAgYgbQgIAKAAARQAAASAIALQAKALAOAAQAPAAAKgLQAIgLAAgSQAAgRgIgKQgKgMgPAAQgPAAgJAMg");
	this.shape_24.setTransform(207.75,337.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F4EFEF").s().p("AAbBMIgpg0IgPANIAAAnIgUAAIAAiWIAUAAIAABcIA0gvIAZAAIgwArIAyA+g");
	this.shape_25.setTransform(196.6,335.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F4EFEF").s().p("AgJBMIAAiWIATAAIAACWg");
	this.shape_26.setTransform(187.9,335.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F4EFEF").s().p("AgtAMIAAhBIAUAAIAAA/QAAAcAYAAQALAAAIgIQAIgKAAgOIAAg7IAUAAIAABoIgUAAIAAgTQgEAKgJAGQgKAGgKAAQgmAAAAgqg");
	this.shape_27.setTransform(179.625,337.95);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F4EFEF").s().p("AAbA2IAAg/QAAgcgZAAQgLAAgIAJQgJAJAAAOIAAA7IgUAAIAAhoIAUAAIAAATQAEgKAKgFQAJgHALAAQAUAAAKANQAJAKAAAUIAABAg");
	this.shape_28.setTransform(163.625,337.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F4EFEF").s().p("AglAoQgPgPAAgZQAAgXAPgQQAOgPAXAAQAXAAAPAPQAQAQAAAXQAAAZgQAPQgPAQgXAAQgXAAgOgQgAgYgbQgIAKAAARQAAASAIALQAKALAOAAQAPAAAKgLQAIgLAAgSQAAgRgIgKQgKgMgPAAQgPAAgJAMg");
	this.shape_29.setTransform(151.6,337.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F4EFEF").s().p("AgJBMIAAhpIATAAIAABpgAgKg0IAAgWIAVAAIAAAWg");
	this.shape_30.setTransform(143.2,335.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F4EFEF").s().p("AgRApIAAhBIgQAAIAAgLIAHgBQAGgBAEgEQACgEACgIIADgOIALAAIAAAcIAdAAIAAAPIgdAAIAAA/QgBAOANgBQAJAAALgGIAAANQgMAKgOAAQgZgBAAgbg");
	this.shape_31.setTransform(137.1,336.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F4EFEF").s().p("AgtAMIAAhBIAUAAIAAA/QAAAcAYAAQALAAAIgIQAIgKAAgOIAAg7IAUAAIAABoIgUAAIAAgTQgEAKgJAGQgKAGgKAAQgmAAAAgqg");
	this.shape_32.setTransform(127.625,337.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F4EFEF").s().p("AgtAMIAAhBIAUAAIAAA/QAAAcAYAAQALAAAIgIQAIgKAAgOIAAg7IAUAAIAABoIgUAAIAAgTQgEAKgJAGQgKAGgKAAQgmAAAAgqg");
	this.shape_33.setTransform(115.875,337.95);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#F4EFEF").s().p("AAbBMIgpg0IgPANIAAAnIgUAAIAAiWIAUAAIAABcIA0gvIAZAAIgwArIAyA+g");
	this.shape_34.setTransform(104.95,335.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F4EFEF").s().p("AgbAJIAAgRIA3AAIAAARg");
	this.shape_35.setTransform(90.175,336.925);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#F4EFEF").s().p("AgdAuQgOgKgBgTIARgBQACAZAbAAQAZAAAAgQQAAgHgGgEQgEgDgKgBIgRgDQgggGAAgXQAAgPAMgIQALgJASAAQAqAAADAlIgQABQgEgXgZgBQgKAAgGAFQgGAEAAAHQAAAMAQADIATACQAhAGAAAYQAAAPgMAJQgLAIgUABQgTAAgMgKg");
	this.shape_36.setTransform(76.55,337.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#F4EFEF").s().p("AgZBJIARgpIgthoIAVAAIAhBQIABAAIAghQIAUAAIg8CRg");
	this.shape_37.setTransform(65.925,339.825);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#F4EFEF").s().p("AgrBEQgJgIAAgNQgBgOAMgIQAKgHAUgEIAcgGIAAgEQAAgKgGgGQgGgGgKAAQgVAAgFAUIgSgCQADgPAMgJQALgKASAAQApAAAAAoIAAAvQAAAIAIAAQAGAAADgDIAAALQgGAGgJAAQgJAAgFgFQgFgGgCgJQgEAJgKAGQgJAGgNAAQgQAAgIgIgAgFAaQgPAEgFADQgIAEABAJQgBAQATAAQAOAAAHgKQAKgKAAgQIAAgFgAADg0IAAgXIATAAIAAAXgAgeg0IAAgXIAUAAIAAAXg");
	this.shape_38.setTransform(54.9,335.725);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#F4EFEF").s().p("AgeAuQgNgKgBgTIARgBQACAZAbAAQAZAAAAgQQAAgHgGgEQgDgDgLgBIgRgDQgfgGgBgXQABgPAKgIQAMgJASAAQAqAAADAlIgQABQgEgXgZgBQgKAAgGAFQgGAEAAAHQAAAMAQADIATACQAhAGABAYQAAAPgNAJQgLAIgUABQgTAAgNgKg");
	this.shape_39.setTransform(43.5,337.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#F4EFEF").s().p("AgZBJIARgpIgthoIAVAAIAhBQIABAAIAghQIAUAAIg8CRg");
	this.shape_40.setTransform(32.875,339.825);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#F4EFEF").s().p("AgpA/QgSgPAAgaIASgBQABATANALQAMALATAAQARAAAKgHQAKgHAAgMQAAgLgHgFQgHgFgPgDIgdgGQgmgHAAggQAAgUAPgMQAOgMAZAAQAbAAAQAOQAQAOAAAaIgTABQAAgTgLgLQgLgJgSgBQgQABgJAGQgJAIAAAMQAAALAHAFQAGAFAPADIAaAFQAVAEAKAIQAKALAAARQAAAVgQAMQgPALgZABQgcgBgRgPg");
	this.shape_41.setTransform(20.475,335.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16}]},60).wait(65));

	// VIERAILE
	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#F4EFEF").s().p("AgvA0QgKgJAAgPQAAgPANgIQAKgHAXgEIAegGIAAgFQgBgMgGgHQgHgGgKAAQgXAAgGAXIgTgDQADgRAMgJQANgLAUAAQAsAAAAArIAAAzQAAAJAJAAQAFgBAFgCIAAAMQgHAGgLABQgIAAgGgHQgFgGgBgKQgFAKgMAGQgKAHgOAAQgQAAgKgIgAgGAHQgQADgFADQgIAFAAAJQAAARATAAQAPAAAKgKQAJgLABgQIAAgGg");
	this.shape_42.setTransform(257.15,460.85);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#F4EFEF").s().p("AggAyQgPgLgBgUIASgBQADAaAeAAQAaAAAAgRQAAgHgGgEQgEgEgMgCIgSgDQgigFAAgaQAAgPAMgKQAMgKAUAAQAuAAADApIgSAAQgDgZgcAAQgLAAgGAFQgHAEAAAIQAAANASADIAUADQAkAHAAAaQAAAQgNAJQgNAJgUAAQgVAAgOgKg");
	this.shape_43.setTransform(244.775,460.85);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#F4EFEF").s().p("AggAyQgPgLgBgUIASgBQADAaAeAAQAaAAAAgRQAAgHgGgEQgEgEgMgCIgSgDQgigFAAgaQAAgPAMgKQAMgKAUAAQAuAAADApIgSAAQgDgZgcAAQgLAAgGAFQgHAEAAAIQAAANASADIAUADQAkAHAAAaQAAAQgNAJQgNAJgUAAQgVAAgOgKg");
	this.shape_44.setTransform(233.525,460.85);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#F4EFEF").s().p("AgnAsQgQgQAAgaQAAgaAQgSQARgRAYAAQAZAAAPARQAOAPAAAZIAAAIIhZAAQABAQAKALQAKAKAPAAQAbAAAIgaIASACQgEATgOALQgOALgWAAQgYAAgRgQgAAigIQgBgOgHgKQgKgLgOAAQgOAAgKALQgJAKgCAOIBDAAIAAAAg");
	this.shape_45.setTransform(221.6,460.85);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#F4EFEF").s().p("AgiA7IAAhxIAWAAIAAAXQADgKAIgIQAIgIALAAQAKAAAHAFIgCAUQgJgFgJAAQgNAAgGAKQgIAKAAAQIAAA8g");
	this.shape_46.setTransform(211.65,460.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#F4EFEF").s().p("AgvA0QgKgJAAgPQAAgPANgIQAKgHAXgEIAegGIAAgFQgBgMgGgHQgHgGgLAAQgWAAgGAXIgTgDQADgRANgJQAMgLAUAAQAsAAAAArIAAAzQAAAJAJAAQAGgBAEgCIAAAMQgHAGgLABQgIAAgGgHQgFgGgCgKQgEAKgMAGQgKAHgNAAQgRAAgKgIgAgGAHQgPADgGADQgJAFABAJQgBARAUAAQAPAAAKgKQAKgLAAgQIAAgGg");
	this.shape_47.setTransform(200.65,460.85);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#F4EFEF").s().p("AgvA0QgKgJAAgPQAAgPANgIQAKgHAXgEIAegGIAAgFQgBgMgGgHQgHgGgLAAQgWAAgGAXIgTgDQADgRANgJQAMgLAUAAQAsAAAAArIAAAzQAAAJAJAAQAFgBAFgCIAAAMQgHAGgLABQgIAAgGgHQgFgGgCgKQgEAKgMAGQgKAHgOAAQgQAAgKgIgAgGAHQgQADgFADQgJAFABAJQAAARATAAQAQAAAJgKQAKgLAAgQIAAgGg");
	this.shape_48.setTransform(187.95,460.85);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#F4EFEF").s().p("AggAyQgPgLgBgUIASgBQADAaAeAAQAaAAAAgRQAAgHgGgEQgEgEgMgCIgSgDQgigFAAgaQAAgPAMgKQAMgKAUAAQAuAAADApIgSAAQgDgZgcAAQgLAAgGAFQgHAEAAAIQAAANASADIAUADQAkAHAAAaQAAAQgNAJQgNAJgUAAQgVAAgOgKg");
	this.shape_49.setTransform(175.575,460.85);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#F4EFEF").s().p("AgKBSIAAhwIAVAAIAABwgAgKg4IAAgZIAVAAIAAAZg");
	this.shape_50.setTransform(167.5,458.35);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#F4EFEF").s().p("ABBA7IAAhEQAAgfgZAAQgNAAgIAJQgJAKAAAPIAABBIgUAAIAAhEQAAgfgZAAQgNAAgHAJQgJAKAAAPIAABBIgVAAIAAhxIAVAAIAAAUQAEgLAJgFQALgIAMABQAcAAAIAZQAFgLAKgHQAKgHANAAQAogBABAvIAABGg");
	this.shape_51.setTransform(154.95,460.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#F4EFEF").s().p("ABBA7IAAhEQAAgfgZAAQgMAAgJAJQgJAKAAAPIAABBIgUAAIAAhEQAAgfgZAAQgMAAgJAJQgIAKAAAPIAABBIgVAAIAAhxIAVAAIAAAUQAEgLAKgFQAJgIANABQAcAAAIAZQAFgLAKgHQAKgHANAAQAogBABAvIAABGg");
	this.shape_52.setTransform(134.8,460.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#F4EFEF").s().p("AgvA0QgKgJAAgPQAAgPANgIQALgHAWgEIAegGIAAgFQgBgMgGgHQgHgGgLAAQgWAAgGAXIgTgDQADgRANgJQANgLATAAQAsAAAAArIAAAzQAAAJAJAAQAFgBAFgCIAAAMQgHAGgLABQgIAAgGgHQgFgGgCgKQgEAKgMAGQgKAHgOAAQgQAAgKgIgAgGAHQgQADgFADQgJAFABAJQAAARATAAQAQAAAJgKQAKgLAAgQIAAgGg");
	this.shape_53.setTransform(118.65,460.85);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#F4EFEF").s().p("AgLBSIAAiQIg7AAIAAgTICNAAIAAATIg8AAIAACQg");
	this.shape_54.setTransform(104.325,458.35);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#F4EFEF").s().p("AgmAsQgRgQAAgaQAAgaARgSQAPgRAYAAQAbAAAPARQANAPAAAZIAAAIIhaAAQABAQALALQALAKAOAAQAcAAAGgaIASACQgEATgOALQgOALgVAAQgYAAgQgQgAAigIQAAgOgJgKQgJgLgPAAQgNAAgKALQgJAKgCAOIBDAAIAAAAg");
	this.shape_55.setTransform(85.65,460.85);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#F4EFEF").s().p("AgKBSIAAijIAVAAIAACjg");
	this.shape_56.setTransform(76.825,458.35);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#F4EFEF").s().p("AgJBSIAAhwIAUAAIAABwgAgKg4IAAgZIAVAAIAAAZg");
	this.shape_57.setTransform(71.75,458.35);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#F4EFEF").s().p("AgvA0QgKgJAAgPQAAgPANgIQAKgHAXgEIAegGIAAgFQgBgMgGgHQgHgGgLAAQgWAAgGAXIgTgDQADgRAMgJQANgLAUAAQAsAAAAArIAAAzQAAAJAJAAQAFgBAFgCIAAAMQgHAGgLABQgIAAgGgHQgFgGgBgKQgFAKgMAGQgKAHgOAAQgQAAgKgIgAgGAHQgQADgFADQgIAFAAAJQAAARATAAQAPAAAKgKQAJgLABgQIAAgGg");
	this.shape_58.setTransform(63.2,460.85);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#F4EFEF").s().p("AgiA7IAAhxIAWAAIAAAXQADgKAIgIQAIgIALAAQAKAAAHAFIgCAUQgJgFgJAAQgMAAgHAKQgJAKABAQIAAA8g");
	this.shape_59.setTransform(52.9,460.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#F4EFEF").s().p("AgmAsQgRgQAAgaQAAgaARgSQAPgRAYAAQAbAAAPARQANAPAAAZIAAAIIhaAAQABAQALALQALAKAOAAQAcAAAGgaIASACQgEATgOALQgOALgVAAQgYAAgQgQgAAigIQAAgOgJgKQgJgLgPAAQgNAAgKALQgJAKgCAOIBDAAIAAAAg");
	this.shape_60.setTransform(41.55,460.85);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#F4EFEF").s().p("AgJBSIAAhwIAUAAIAABwgAgKg4IAAgZIAVAAIAAAZg");
	this.shape_61.setTransform(32.7,458.35);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#F4EFEF").s().p("AgLBSIhCijIAXAAIA2CJIABAAIA2iJIAXAAIhCCjg");
	this.shape_62.setTransform(22.025,458.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42}]},104).wait(21));

	// _0_10_2025
	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#F4EFEF").s().p("AgtA/QgRgVAAgnQAAgnAQgXQASgZAgAAQAZAAAPANQAQANACAXIgWABQgFgggfAAQgXAAgMAVQgLASAAAiQAEgOAMgJQAOgKASAAQAaAAAQAQQAPAOAAAYQAAAZgQARQgQAPgcAAQgfAAgRgWgAgZABQgLAKAAASQAAARALAKQALALARAAQASAAAKgLQALgKAAgRQAAgSgLgKQgKgJgTAAQgRAAgKAJg");
	this.shape_63.setTransform(233.625,363.1);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_64.setTransform(220.025,362.95);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#F4EFEF").s().p("AgxA/QgSgWAAgpQAAgnASgWQASgXAfAAQAgAAASAXQASAWAAAnQAAApgSAWQgSAWggAAQgfAAgSgWgAgrAAQAABDArAAQAsAAABhDQgBhCgsABQgrgBAABCg");
	this.shape_65.setTransform(205.75,363.1);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_66.setTransform(191.675,362.95);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#F4EFEF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_67.setTransform(182.75,370);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_68.setTransform(174.025,362.95);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#F4EFEF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_69.setTransform(165.1,370);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_70.setTransform(156.375,362.95);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_71.setTransform(143.275,362.95);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#F4EFEF").s().p("AgxAIIAAgPIBjAAIAAAPg");
	this.shape_72.setTransform(130.1,364.675);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#F4EFEF").s().p("AgsBCQgQgQABgcIAWACQAAAUAKAKQAKAMASAAQARAAALgLQAJgLAAgRQAAgRgJgKQgLgKgRAAQgYAAgLAUIgWgBQAJgyABgqIBfAAIAAAVIhNAAIgDAZIgDAZQAOgQAYAAQAbAAAPAQQAOAOAAAYQAAAagQAPQgRAQgaABQgdgBgQgRg");
	this.shape_73.setTransform(116.897,363.25);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_74.setTransform(103.525,362.95);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#F4EFEF").s().p("AgxA/QgSgWAAgpQAAgnASgWQARgXAgAAQAgAAASAXQASAWAAAnQAAApgSAWQgSAWggAAQggAAgRgWgAgsAAQAABDAsAAQAsAAAAhDQAAhCgsABQgsgBAABCg");
	this.shape_75.setTransform(89.25,363.1);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#F4EFEF").s().p("Ag7BUIAAgOIAugnQAXgWAIgJQANgPAAgQQAAgPgIgJQgIgJgPAAQgRAAgJAKQgJAKAAASQAAAIACAHIgXgBIgBgQQAAgZAPgOQAQgPAaAAQAaAAAPAPQAOANAAAWQAAAUgQATQgKAMgXAUIgeAZIBUAAIAAAUg");
	this.shape_76.setTransform(75.175,362.95);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#F4EFEF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_77.setTransform(66.25,370);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#F4EFEF").s().p("AgxA/QgSgWAAgpQAAgnASgWQASgXAfAAQAgAAASAXQASAWAAAnQAAApgSAWQgSAWggAAQgfAAgSgWgAgrAAQAABDArAAQAsAAABhDQgBhCgsABQgrgBAABCg");
	this.shape_78.setTransform(56.35,363.1);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#F4EFEF").s().p("AAEBTIAAh9IgeAAIAAgPQARABAJgHQAHgFAFgOIAPAAIAAClg");
	this.shape_79.setTransform(44.125,363.05);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#F4EFEF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape_80.setTransform(38.95,370);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#F4EFEF").s().p("AgxA/QgSgWAAgpQAAgnASgWQASgXAfAAQAgAAASAXQASAWAAAnQAAApgSAWQgSAWggAAQgfAAgSgWgAgsAAQAABDAsAAQAsAAAAhDQAAhCgsABQgsgBAABCg");
	this.shape_81.setTransform(29.05,363.1);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#F4EFEF").s().p("AAEBTIAAh9IgeAAIAAgPQARABAJgHQAHgFAFgOIAPAAIAAClg");
	this.shape_82.setTransform(16.825,363.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63}]},80).wait(45));

	// TAUSTA
	this.instance_1 = new lib.GREENBACKGROUNDSYMBOL("synched",0);
	this.instance_1.setTransform(157,307,1,1,0,0,0,175,325);

	this.instance_2 = new lib.Symbol2("synched",0);
	this.instance_2.setTransform(171.35,319.1,1.0189,1.0189,0,0,0,184,341.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({scaleX:1.0006,scaleY:1.0006,x:157.15,y:307.15},0).wait(1).to({scaleX:1.0012,scaleY:1.0012,x:157.25,y:307.2},0).wait(1).to({scaleX:1.0017,scaleY:1.0017,x:157.35,y:307.3},0).wait(1).to({scaleX:1.0023,scaleY:1.0023,x:157.5,y:307.4},0).wait(1).to({scaleX:1.0029,scaleY:1.0029,x:157.6,y:307.5},0).wait(1).to({scaleX:1.0035,scaleY:1.0035,x:157.7,y:307.65},0).wait(1).to({scaleX:1.0041,scaleY:1.0041,x:157.85,y:307.7},0).wait(1).to({scaleX:1.0046,scaleY:1.0046,x:157.95,y:307.8},0).wait(1).to({scaleX:1.0052,scaleY:1.0052,x:158.05,y:307.9},0).wait(1).to({scaleX:1.0058,scaleY:1.0058,x:158.15,y:308},0).wait(1).to({scaleX:1.0064,scaleY:1.0064,x:158.3,y:308.1},0).wait(1).to({scaleX:1.007,scaleY:1.0069,x:158.4,y:308.2},0).wait(1).to({scaleX:1.0075,scaleY:1.0075,x:158.5,y:308.3},0).wait(1).to({scaleX:1.0081,scaleY:1.0081,x:158.65,y:308.4},0).wait(1).to({scaleX:1.0087,scaleY:1.0087,x:158.75,y:308.45},0).wait(1).to({scaleX:1.0093,scaleY:1.0093,x:158.85,y:308.6},0).wait(1).to({scaleX:1.0099,scaleY:1.0098,x:159,y:308.7},0).wait(1).to({scaleX:1.0104,scaleY:1.0104,x:159.1,y:308.8},0).wait(1).to({scaleX:1.011,scaleY:1.011,x:159.25,y:308.85},0).wait(1).to({scaleX:1.0116,scaleY:1.0116,x:159.35,y:308.95},0).wait(1).to({scaleX:1.0122,scaleY:1.0122,x:159.5,y:309.1},0).wait(1).to({scaleX:1.0128,scaleY:1.0127,x:159.6,y:309.2},0).wait(1).to({scaleX:1.0133,scaleY:1.0133,x:159.7,y:309.25},0).wait(1).to({scaleX:1.0139,scaleY:1.0139,x:159.85,y:309.35},0).wait(1).to({scaleX:1.0145,scaleY:1.0145,x:159.95,y:309.45},0).wait(1).to({scaleX:1.0151,scaleY:1.015,x:160.05,y:309.6},0).wait(1).to({scaleX:1.0157,scaleY:1.0156,x:160.2,y:309.65},0).wait(1).to({scaleX:1.0162,scaleY:1.0162,x:160.3,y:309.75},0).wait(1).to({scaleX:1.0168,scaleY:1.0168,x:160.4,y:309.85},0).wait(1).to({scaleX:1.0174,scaleY:1.0174,x:160.5,y:309.95},0).wait(1).to({scaleX:1.018,scaleY:1.0179,x:160.65,y:310.1},0).wait(1).to({scaleX:1.0185,scaleY:1.0185,x:160.75,y:310.15},0).wait(1).to({scaleX:1.0191,scaleY:1.0191,x:160.85,y:310.25},0).wait(1).to({scaleX:1.0197,scaleY:1.0197,x:161,y:310.35},0).wait(1).to({scaleX:1.0203,scaleY:1.0203,x:161.1,y:310.45},0).wait(1).to({scaleX:1.0209,scaleY:1.0208,x:161.2,y:310.55},0).wait(1).to({scaleX:1.0214,scaleY:1.0214,x:161.3,y:310.65},0).wait(1).to({scaleX:1.022,scaleY:1.022,x:161.45,y:310.75},0).wait(1).to({scaleX:1.0226,scaleY:1.0226,x:161.55,y:310.85},0).wait(1).to({scaleX:1.0232,scaleY:1.0231,x:161.65,y:310.9},0).wait(1).to({scaleX:1.0238,scaleY:1.0237,x:161.8,y:311.05},0).wait(1).to({scaleX:1.0243,scaleY:1.0243,x:161.9,y:311.15},0).wait(1).to({scaleX:1.0249,scaleY:1.0249,x:162,y:311.25},0).wait(1).to({scaleX:1.0255,scaleY:1.0255,x:162.15,y:311.3},0).wait(1).to({scaleX:1.0261,scaleY:1.026,x:162.25,y:311.4},0).wait(1).to({scaleX:1.0267,scaleY:1.0266,x:162.35,y:311.55},0).wait(1).to({scaleX:1.0272,scaleY:1.0272,x:162.45,y:311.65},0).wait(1).to({scaleX:1.0278,scaleY:1.0278,x:162.6,y:311.75},0).wait(1).to({scaleX:1.0284,scaleY:1.0284,x:162.7,y:311.8},0).wait(1).to({scaleX:1.029,scaleY:1.0289,x:162.8,y:311.9},0).wait(1).to({scaleX:1.0296,scaleY:1.0295,x:162.95,y:312.05},0).wait(1).to({scaleX:1.0301,scaleY:1.0301,x:163.05,y:312.1},0).wait(1).to({scaleX:1.0307,scaleY:1.0307,x:163.2,y:312.2},0).wait(1).to({scaleX:1.0313,scaleY:1.0312,x:163.35,y:312.3},0).wait(1).to({scaleX:1.0319,scaleY:1.0318,x:163.45,y:312.4},0).wait(1).to({scaleX:1.0325,scaleY:1.0324,x:163.55,y:312.55},0).wait(1).to({scaleX:1.033,scaleY:1.033,x:163.65,y:312.6},0).wait(1).to({scaleX:1.0336,scaleY:1.0336,x:163.8,y:312.7},0).wait(1).to({scaleX:1.0342,scaleY:1.0341,x:163.9,y:312.8},0).wait(1).to({scaleX:1.0348,scaleY:1.0347,x:164,y:312.9},0).wait(1).to({scaleX:1.0354,scaleY:1.0353,x:164.15,y:313},0).wait(1).to({scaleX:1.0359,scaleY:1.0359,x:164.25,y:313.1},0).wait(1).to({scaleX:1.0365,scaleY:1.0365,x:164.35,y:313.2},0).wait(1).to({scaleX:1.0371,scaleY:1.037,x:164.45,y:313.3},0).wait(1).to({scaleX:1.0377,scaleY:1.0376,x:164.6,y:313.35},0).wait(1).to({scaleX:1.0383,scaleY:1.0382,x:164.7,y:313.5},0).wait(1).to({scaleX:1.0388,scaleY:1.0388,x:164.8,y:313.6},0).wait(1).to({scaleX:1.0394,scaleY:1.0393,x:164.95,y:313.7},0).wait(1).to({scaleX:1.04,scaleY:1.0399,x:165.05,y:313.75},0).wait(1).to({scaleX:1.0406,scaleY:1.0405,x:165.15,y:313.85},0).wait(1).to({scaleX:1.0412,scaleY:1.0411,x:165.3,y:314},0).wait(1).to({scaleX:1.0417,scaleY:1.0417,x:165.4,y:314.1},0).wait(1).to({scaleX:1.0423,scaleY:1.0422,x:165.5,y:314.2},0).wait(1).to({scaleX:1.0429,scaleY:1.0428,x:165.6,y:314.25},0).wait(1).to({scaleX:1.0435,scaleY:1.0434,x:165.75,y:314.35},0).wait(1).to({scaleX:1.0441,scaleY:1.044,x:165.85,y:314.5},0).wait(1).to({scaleX:1.0446,scaleY:1.0446,x:165.95,y:314.6},0).wait(1).to({scaleX:1.0452,scaleY:1.0451,x:166.1,y:314.65},0).wait(1).to({scaleX:1.0458,scaleY:1.0457,x:166.2,y:314.75},0).wait(1).to({scaleX:1.0464,scaleY:1.0463,x:166.3,y:314.85},0).wait(1).to({scaleX:1.047,scaleY:1.0469,x:166.45,y:315},0).wait(1).to({scaleX:1.0475,scaleY:1.0474,x:166.55,y:315.05},0).wait(1).to({scaleX:1.0481,scaleY:1.048,x:166.65,y:315.15},0).wait(1).to({scaleX:1.0487,scaleY:1.0486,x:166.75,y:315.25},0).wait(1).to({scaleX:1.0493,scaleY:1.0492,x:166.9,y:315.35},0).wait(1).to({scaleX:1.0499,scaleY:1.0498,x:167,y:315.45},0).wait(1).to({scaleX:1.0504,scaleY:1.0503,x:167.15,y:315.55},0).wait(1).to({scaleX:1.051,scaleY:1.0509,x:167.3,y:315.65},0).wait(1).to({scaleX:1.0516,scaleY:1.0515,x:167.4,y:315.75},0).wait(1).to({scaleX:1.0522,scaleY:1.0521,x:167.5,y:315.8},0).wait(1).to({scaleX:1.0528,scaleY:1.0527,x:167.6,y:315.95},0).wait(1).to({scaleX:1.0533,scaleY:1.0532,x:167.75,y:316.05},0).wait(1).to({scaleX:1.0539,scaleY:1.0538,x:167.85,y:316.15},0).wait(1).to({scaleX:1.0545,scaleY:1.0544,x:167.95,y:316.2},0).wait(1).to({scaleX:1.0551,scaleY:1.055,x:168.1,y:316.3},0).wait(1).to({scaleX:1.0556,scaleY:1.0555,x:168.2,y:316.45},0).wait(1).to({scaleX:1.0562,scaleY:1.0561,x:168.3,y:316.55},0).wait(1).to({scaleX:1.0568,scaleY:1.0567,x:168.45,y:316.65},0).wait(1).to({scaleX:1.0574,scaleY:1.0573,x:168.55,y:316.7},0).wait(1).to({scaleX:1.058,scaleY:1.0579,x:168.65,y:316.8},0).wait(1).to({scaleX:1.0585,scaleY:1.0584,x:168.75,y:316.95},0).wait(1).to({scaleX:1.0591,scaleY:1.059,x:168.9,y:317.05},0).wait(1).to({scaleX:1.0597,scaleY:1.0596,x:169,y:317.1},0).wait(1).to({scaleX:1.0603,scaleY:1.0602,x:169.1,y:317.2},0).wait(1).to({scaleX:1.0609,scaleY:1.0608,x:169.25,y:317.3},0).wait(1).to({scaleX:1.0614,scaleY:1.0613,x:169.35,y:317.45},0).wait(1).to({scaleX:1.062,scaleY:1.0619,x:169.45,y:317.5},0).wait(1).to({scaleX:1.0626,scaleY:1.0625,x:169.6,y:317.6},0).wait(1).to({scaleX:1.0632,scaleY:1.0631,x:169.7,y:317.7},0).wait(1).to({scaleX:1.0638,scaleY:1.0636,x:169.8,y:317.8},0).wait(1).to({scaleX:1.0643,scaleY:1.0642,x:169.9,y:317.9},0).wait(1).to({scaleX:1.0649,scaleY:1.0648,x:170.05,y:318},0).wait(1).to({scaleX:1.0655,scaleY:1.0654,x:170.15,y:318.1},0).wait(1).to({scaleX:1.0661,scaleY:1.066,x:170.25,y:318.2},0).wait(1).to({scaleX:1.0667,scaleY:1.0665,x:170.4,y:318.25},0).wait(1).to({scaleX:1.0672,scaleY:1.0671,x:170.5,y:318.4},0).wait(1).to({scaleX:1.0678,scaleY:1.0677,x:170.6,y:318.5},0).wait(1).to({scaleX:1.0684,scaleY:1.0683,x:170.7,y:318.6},0).wait(1).to({scaleX:1.069,scaleY:1.0689,x:170.85,y:318.7},0).wait(1).to({scaleX:1.0696,scaleY:1.0694,x:170.95,y:318.75},0).wait(1).to({scaleX:1.0701,scaleY:1.07,x:171.05,y:318.85},0).wait(1).to({scaleX:1.0707,scaleY:1.0706,x:171.2,y:319},0).wait(1).to({scaleX:1.0713,scaleY:1.0712,x:171.35,y:319.1},0).to({_off:true},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-60.7,-40.1,581.2,707.4);
// library properties:
lib.properties = {
	id: '91BD5B478140452D96C560DE2722B194',
	width: 300,
	height: 600,
	fps: 25,
	color: "#000000",
	opacity: 1.00,
	manifest: [
		{src:"images/Sysaysbackground300x600.jpg?1761422650888", id:"Sysaysbackground300x600"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['91BD5B478140452D96C560DE2722B194'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;